//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api-provider-azure/api/v1beta1"
	apiv1beta1 "sigs.k8s.io/cluster-api-provider-gcp/exp/api/v1beta1"
	"sigs.k8s.io/cluster-api/errors"
	expapiv1beta1 "sigs.k8s.io/cluster-api/exp/api/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSCloudSpec) DeepCopyInto(out *AWSCloudSpec) {
	*out = *in
	out.ClusterAPIComponentSpec = in.ClusterAPIComponentSpec
	if in.ServiceAccounts != nil {
		in, out := &in.ServiceAccounts, &out.ServiceAccounts
		*out = make([]ClusterIAMServiceAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Addons != nil {
		in, out := &in.Addons, &out.Addons
		*out = make([]Addon, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.AccessKeyIDRef.DeepCopyInto(&out.AccessKeyIDRef)
	in.SecretAccessKeyRef.DeepCopyInto(&out.SecretAccessKeyRef)
	in.SessionTokenRef.DeepCopyInto(&out.SessionTokenRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSCloudSpec.
func (in *AWSCloudSpec) DeepCopy() *AWSCloudSpec {
	if in == nil {
		return nil
	}
	out := new(AWSCloudSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Addon) DeepCopyInto(out *Addon) {
	*out = *in
	if in.ServiceAccountRoleArn != nil {
		in, out := &in.ServiceAccountRoleArn, &out.ServiceAccountRoleArn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Addon.
func (in *Addon) DeepCopy() *Addon {
	if in == nil {
		return nil
	}
	out := new(Addon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureCloudSpec) DeepCopyInto(out *AzureCloudSpec) {
	*out = *in
	if in.ManagedCluster != nil {
		in, out := &in.ManagedCluster, &out.ManagedCluster
		*out = new(v1beta1.AzureManagedClusterSpec)
		**out = **in
	}
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(v1beta1.AzureManagedControlPlaneSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MachinePool != nil {
		in, out := &in.MachinePool, &out.MachinePool
		*out = new(AzureMachinePoolSpec)
		**out = **in
	}
	in.CredentialsRef.DeepCopyInto(&out.CredentialsRef)
	out.ClusterAPIComponentSpec = in.ClusterAPIComponentSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureCloudSpec.
func (in *AzureCloudSpec) DeepCopy() *AzureCloudSpec {
	if in == nil {
		return nil
	}
	out := new(AzureCloudSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureMachinePoolSpec) DeepCopyInto(out *AzureMachinePoolSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureMachinePoolSpec.
func (in *AzureMachinePoolSpec) DeepCopy() *AzureMachinePoolSpec {
	if in == nil {
		return nil
	}
	out := new(AzureMachinePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Bootstrap) DeepCopyInto(out *Bootstrap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Bootstrap.
func (in *Bootstrap) DeepCopy() *Bootstrap {
	if in == nil {
		return nil
	}
	out := new(Bootstrap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Bootstrap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapList) DeepCopyInto(out *BootstrapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Bootstrap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapList.
func (in *BootstrapList) DeepCopy() *BootstrapList {
	if in == nil {
		return nil
	}
	out := new(BootstrapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BootstrapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapSpec) DeepCopyInto(out *BootstrapSpec) {
	*out = *in
	in.ClusterNetwork.DeepCopyInto(&out.ClusterNetwork)
	in.ClusterAPI.DeepCopyInto(&out.ClusterAPI)
	in.CloudSpec.DeepCopyInto(&out.CloudSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapSpec.
func (in *BootstrapSpec) DeepCopy() *BootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(BootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapStatus) DeepCopyInto(out *BootstrapStatus) {
	*out = *in
	out.Status = in.Status
	if in.CapiOperatorStatus != nil {
		in, out := &in.CapiOperatorStatus, &out.CapiOperatorStatus
		*out = new(Status)
		**out = **in
	}
	if in.CapiOperatorComponentsStatus != nil {
		in, out := &in.CapiOperatorComponentsStatus, &out.CapiOperatorComponentsStatus
		*out = new(Status)
		**out = **in
	}
	if in.CapiClusterStatus != nil {
		in, out := &in.CapiClusterStatus, &out.CapiClusterStatus
		*out = new(ClusterStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ProviderStatus != nil {
		in, out := &in.ProviderStatus, &out.ProviderStatus
		*out = new(Status)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapStatus.
func (in *BootstrapStatus) DeepCopy() *BootstrapStatus {
	if in == nil {
		return nil
	}
	out := new(BootstrapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudSpec) DeepCopyInto(out *CloudSpec) {
	*out = *in
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSCloudSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureCloudSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(GCPCloudSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudSpec.
func (in *CloudSpec) DeepCopy() *CloudSpec {
	if in == nil {
		return nil
	}
	out := new(CloudSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAPI) DeepCopyInto(out *ClusterAPI) {
	*out = *in
	in.Components.DeepCopyInto(&out.Components)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAPI.
func (in *ClusterAPI) DeepCopy() *ClusterAPI {
	if in == nil {
		return nil
	}
	out := new(ClusterAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAPIBootstrap) DeepCopyInto(out *ClusterAPIBootstrap) {
	*out = *in
	out.ClusterAPIComponentSpec = in.ClusterAPIComponentSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAPIBootstrap.
func (in *ClusterAPIBootstrap) DeepCopy() *ClusterAPIBootstrap {
	if in == nil {
		return nil
	}
	out := new(ClusterAPIBootstrap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAPIComponentSpec) DeepCopyInto(out *ClusterAPIComponentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAPIComponentSpec.
func (in *ClusterAPIComponentSpec) DeepCopy() *ClusterAPIComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterAPIComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAPIComponents) DeepCopyInto(out *ClusterAPIComponents) {
	*out = *in
	out.Operator = in.Operator
	if in.Core != nil {
		in, out := &in.Core, &out.Core
		*out = new(ClusterAPICore)
		**out = **in
	}
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(ClusterAPIControlPlane)
		**out = **in
	}
	if in.Bootstrap != nil {
		in, out := &in.Bootstrap, &out.Bootstrap
		*out = new(ClusterAPIBootstrap)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAPIComponents.
func (in *ClusterAPIComponents) DeepCopy() *ClusterAPIComponents {
	if in == nil {
		return nil
	}
	out := new(ClusterAPIComponents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAPIControlPlane) DeepCopyInto(out *ClusterAPIControlPlane) {
	*out = *in
	out.ClusterAPIComponentSpec = in.ClusterAPIComponentSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAPIControlPlane.
func (in *ClusterAPIControlPlane) DeepCopy() *ClusterAPIControlPlane {
	if in == nil {
		return nil
	}
	out := new(ClusterAPIControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAPICore) DeepCopyInto(out *ClusterAPICore) {
	*out = *in
	out.ClusterAPIComponentSpec = in.ClusterAPIComponentSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAPICore.
func (in *ClusterAPICore) DeepCopy() *ClusterAPICore {
	if in == nil {
		return nil
	}
	out := new(ClusterAPICore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAPIOperator) DeepCopyInto(out *ClusterAPIOperator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAPIOperator.
func (in *ClusterAPIOperator) DeepCopy() *ClusterAPIOperator {
	if in == nil {
		return nil
	}
	out := new(ClusterAPIOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIAMServiceAccount) DeepCopyInto(out *ClusterIAMServiceAccount) {
	*out = *in
	in.ClusterIAMMeta.DeepCopyInto(&out.ClusterIAMMeta)
	if in.AttachPolicyARNs != nil {
		in, out := &in.AttachPolicyARNs, &out.AttachPolicyARNs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.WellKnownPolicies = in.WellKnownPolicies
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIAMServiceAccount.
func (in *ClusterIAMServiceAccount) DeepCopy() *ClusterIAMServiceAccount {
	if in == nil {
		return nil
	}
	out := new(ClusterIAMServiceAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNetwork) DeepCopyInto(out *ClusterNetwork) {
	*out = *in
	if in.APIServerPort != nil {
		in, out := &in.APIServerPort, &out.APIServerPort
		*out = new(int32)
		**out = **in
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = new(NetworkRanges)
		(*in).DeepCopyInto(*out)
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = new(NetworkRanges)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNetwork.
func (in *ClusterNetwork) DeepCopy() *ClusterNetwork {
	if in == nil {
		return nil
	}
	out := new(ClusterNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	out.Status = in.Status
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(errors.ClusterStatusError)
		**out = **in
	}
	if in.FailureMessage != nil {
		in, out := &in.FailureMessage, &out.FailureMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPCloudSpec) DeepCopyInto(out *GCPCloudSpec) {
	*out = *in
	if in.ManagedCluster != nil {
		in, out := &in.ManagedCluster, &out.ManagedCluster
		*out = new(apiv1beta1.GCPManagedClusterSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MachinePool != nil {
		in, out := &in.MachinePool, &out.MachinePool
		*out = new(GCPMachinePoolSpec)
		**out = **in
	}
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(apiv1beta1.GCPManagedControlPlaneSpec)
		(*in).DeepCopyInto(*out)
	}
	in.CredentialsRef.DeepCopyInto(&out.CredentialsRef)
	out.ClusterAPIComponentSpec = in.ClusterAPIComponentSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPCloudSpec.
func (in *GCPCloudSpec) DeepCopy() *GCPCloudSpec {
	if in == nil {
		return nil
	}
	out := new(GCPCloudSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPMachinePool) DeepCopyInto(out *GCPMachinePool) {
	*out = *in
	if in.ManagedMachinePool != nil {
		in, out := &in.ManagedMachinePool, &out.ManagedMachinePool
		*out = new(apiv1beta1.GCPManagedMachinePool)
		(*in).DeepCopyInto(*out)
	}
	if in.MachinePool != nil {
		in, out := &in.MachinePool, &out.MachinePool
		*out = new(expapiv1beta1.MachinePool)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPMachinePool.
func (in *GCPMachinePool) DeepCopy() *GCPMachinePool {
	if in == nil {
		return nil
	}
	out := new(GCPMachinePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPMachinePoolSpec) DeepCopyInto(out *GCPMachinePoolSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPMachinePoolSpec.
func (in *GCPMachinePoolSpec) DeepCopy() *GCPMachinePoolSpec {
	if in == nil {
		return nil
	}
	out := new(GCPMachinePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRanges) DeepCopyInto(out *NetworkRanges) {
	*out = *in
	if in.CIDRBlocks != nil {
		in, out := &in.CIDRBlocks, &out.CIDRBlocks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRanges.
func (in *NetworkRanges) DeepCopy() *NetworkRanges {
	if in == nil {
		return nil
	}
	out := new(NetworkRanges)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Status) DeepCopyInto(out *Status) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Status.
func (in *Status) DeepCopy() *Status {
	if in == nil {
		return nil
	}
	out := new(Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WellKnownPolicies) DeepCopyInto(out *WellKnownPolicies) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WellKnownPolicies.
func (in *WellKnownPolicies) DeepCopy() *WellKnownPolicies {
	if in == nil {
		return nil
	}
	out := new(WellKnownPolicies)
	in.DeepCopyInto(out)
	return out
}
