//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSCloudSpec) DeepCopyInto(out *AWSCloudSpec) {
	*out = *in
	out.ClusterAPIComponentSpec = in.ClusterAPIComponentSpec
	in.AccessKeyIDRef.DeepCopyInto(&out.AccessKeyIDRef)
	in.SecretAccessKeyRef.DeepCopyInto(&out.SecretAccessKeyRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSCloudSpec.
func (in *AWSCloudSpec) DeepCopy() *AWSCloudSpec {
	if in == nil {
		return nil
	}
	out := new(AWSCloudSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Bootstrap) DeepCopyInto(out *Bootstrap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Bootstrap.
func (in *Bootstrap) DeepCopy() *Bootstrap {
	if in == nil {
		return nil
	}
	out := new(Bootstrap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Bootstrap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapList) DeepCopyInto(out *BootstrapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Bootstrap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapList.
func (in *BootstrapList) DeepCopy() *BootstrapList {
	if in == nil {
		return nil
	}
	out := new(BootstrapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BootstrapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapSpec) DeepCopyInto(out *BootstrapSpec) {
	*out = *in
	out.Components = in.Components
	in.CloudSpec.DeepCopyInto(&out.CloudSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapSpec.
func (in *BootstrapSpec) DeepCopy() *BootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(BootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapStatus) DeepCopyInto(out *BootstrapStatus) {
	*out = *in
	if in.CapiOperatorStatus != nil {
		in, out := &in.CapiOperatorStatus, &out.CapiOperatorStatus
		*out = new(Status)
		**out = **in
	}
	if in.CapiBootstrap != nil {
		in, out := &in.CapiBootstrap, &out.CapiBootstrap
		*out = new(Status)
		**out = **in
	}
	if in.CapiCore != nil {
		in, out := &in.CapiCore, &out.CapiCore
		*out = new(Status)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapStatus.
func (in *BootstrapStatus) DeepCopy() *BootstrapStatus {
	if in == nil {
		return nil
	}
	out := new(BootstrapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudSpec) DeepCopyInto(out *CloudSpec) {
	*out = *in
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSCloudSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudSpec.
func (in *CloudSpec) DeepCopy() *CloudSpec {
	if in == nil {
		return nil
	}
	out := new(CloudSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAPIBootstrap) DeepCopyInto(out *ClusterAPIBootstrap) {
	*out = *in
	out.ClusterAPIComponentSpec = in.ClusterAPIComponentSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAPIBootstrap.
func (in *ClusterAPIBootstrap) DeepCopy() *ClusterAPIBootstrap {
	if in == nil {
		return nil
	}
	out := new(ClusterAPIBootstrap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAPIComponentSpec) DeepCopyInto(out *ClusterAPIComponentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAPIComponentSpec.
func (in *ClusterAPIComponentSpec) DeepCopy() *ClusterAPIComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterAPIComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAPIComponents) DeepCopyInto(out *ClusterAPIComponents) {
	*out = *in
	out.Operator = in.Operator
	out.Core = in.Core
	out.ControlPlane = in.ControlPlane
	out.Bootstrap = in.Bootstrap
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAPIComponents.
func (in *ClusterAPIComponents) DeepCopy() *ClusterAPIComponents {
	if in == nil {
		return nil
	}
	out := new(ClusterAPIComponents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAPIControlPlane) DeepCopyInto(out *ClusterAPIControlPlane) {
	*out = *in
	out.ClusterAPIComponentSpec = in.ClusterAPIComponentSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAPIControlPlane.
func (in *ClusterAPIControlPlane) DeepCopy() *ClusterAPIControlPlane {
	if in == nil {
		return nil
	}
	out := new(ClusterAPIControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAPICore) DeepCopyInto(out *ClusterAPICore) {
	*out = *in
	out.ClusterAPIComponentSpec = in.ClusterAPIComponentSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAPICore.
func (in *ClusterAPICore) DeepCopy() *ClusterAPICore {
	if in == nil {
		return nil
	}
	out := new(ClusterAPICore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAPIOperator) DeepCopyInto(out *ClusterAPIOperator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAPIOperator.
func (in *ClusterAPIOperator) DeepCopy() *ClusterAPIOperator {
	if in == nil {
		return nil
	}
	out := new(ClusterAPIOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Status) DeepCopyInto(out *Status) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Status.
func (in *Status) DeepCopy() *Status {
	if in == nil {
		return nil
	}
	out := new(Status)
	in.DeepCopyInto(out)
	return out
}
