apiVersion: v1
kind: Namespace
metadata:
  name: bootstrap
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-variables
  namespace: cert-manager
type: Opaque
data:
  AWS_ACCESS_KEY_ID: =
  AWS_SECRET_ACCESS_KEY: =
  AWS_SESSION_TOKEN: =

