---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bootstrap-controller
  namespace: cert-manager
  labels:
    dash.plural.sh/name: bootstrap-controller
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      dash.plural.sh/name: bootstrap-controller
  template:
    metadata:
      labels:
        dash.plural.sh/name: bootstrap-controller
    spec:
      serviceAccountName: bootstrap-controller-sa
      containers:
        - name: bootstrap-controller
          image: zreigz/bootstrap-operator:latest
          args:
            - --namespace=cert-manager
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /tmp
              name: temp
      volumes:
        - name: temp
          emptyDir: {}