---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bootstrap-controller
  labels:
    dash.plural.sh/name: bootstrap-controller
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      dash.plural.sh/name: bootstrap-controller
  template:
    metadata:
      labels:
        dash.plural.sh/name: bootstrap-controller
    spec:
      serviceAccountName: bootstrap-controller-sa
      containers:
        - name: bootstrap-controller
          image: ghcr.io/pluralsh/bootstrap-controller:0.0.8
          imagePullPolicy: Always
